# Generated by Django 2.2.1 on 2019-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('C', 'Clothing'), ('F', 'Furniture'), ('A', 'Accessories'), ('a', 'Automobile'), ('S', 'Stationary')], max_length=255),
        ),
    ]
