# Generated by Django 2.2.1 on 2019-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20191113_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='noitem.jpg', upload_to='item_images/'),
        ),
    ]
